import React from 'react'
import { Toaster } from "@/components/ui/toaster"
import { QueryClientProvider } from '@tanstack/react-query'
import { queryClientInstance } from '@/lib/query-client'
import { BrowserRouter as Router, Route, Routes, useLocation, Navigate } from 'react-router-dom'
import PageNotFound from './lib/PageNotFound'
import { AuthProvider, useAuth } from '@/lib/AuthContext'
import UserNotRegisteredError from '@/components/UserNotRegisteredError'
import ErrorBoundary from '@/components/ErrorBoundary'
import ScrollToTop from './lib/ScrollToTop'
import ProtectedRoute from '@/components/ProtectedRoute'

import AppLayout from './components/layout/AppLayout'
import Dashboard from './pages/Dashboard.jsx'
import CustomerIntelligenceWorkspace from './pages/CustomerIntelligenceWorkspace'
import CustomerDetail from './pages/CustomerDetail'
import Customer360 from './pages/Customer360'
import NewCustomers from './pages/NewCustomers'
import Contracts from './pages/Contracts'
import Applications from './pages/Applications'
import Tasks from './pages/Tasks.jsx'
import Documents from './pages/Documents'
import EmailTemplates from './pages/EmailTemplates'
import EmailCampaigns from './pages/EmailCampaigns'
import StatusVerwaltung from './pages/StatusVerwaltung'
import CommissionsAndCourtage from './pages/CommissionsAndCourtage.jsx'
import BeratungOrganisation from './pages/BeratungOrganisation'
import SystemLogs from './pages/SystemLogs'
import FinanceDashboard from './pages/FinanceDashboard'
import CEODashboard from './components/ceo/CEODashboard'
import CEOCockpit from './pages/CEOCockpit'
import AdvancedDashboard from './pages/AdvancedDashboard'
import ExecutionMode from './pages/ExecutionMode'
import SalesAutopilot from './pages/SalesAutopilot'
import Leads from './pages/Leads'
import CoverageIntelligence from './pages/CoverageIntelligence'
import AdminLogs from './pages/AdminLogs'
import Partners from './pages/Partners'
import PartnerDetail from './pages/PartnerDetail'
import Verkaufschancen from './pages/Verkaufschancen'
import Vertragsablaeufe from './pages/Vertragsablaeufe'
import AdminTeamAccess from './pages/AdminTeamAccess'
import AdvisoryDossier from './packages/AdvisoryD
